name: godot-manual-itch-deploy
on:
  workflow_dispatch:
      inputs:
        tag_name:
          description: 'Name of the Tag to put the release under'     
          required: true
          type: string
      - name: Install Butler
        id: install_butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default \
          && unzip butler.zip \
          && sudo cp butler /usr/bin \
          && sudo chmod +x /usr/bin/butler
      - name: Run Butler Push
        id: butler_push
        run: |
          set -e
          export BUTLER_API_KEY=$BUTLER_CREDENTIALS
          versionArgument=""
          if [[ -z "$VERSION"]]; then
              versionArgument="--userversion ${VERSION}"
          elif [[ -z "$VERSION_FILE"]]; then
              versionArgument="--userversion-file ${VERSION_FILE}"
          fi
          if [[ -z "$HTML5"]]; then
              echo "butler push \"$BASE_URL/$HTML5\" $ITCH_USER/$ITCH_GAME:html5 ${versionArgument}"
              butler push "$BASE_URL/$HTML5" $ITCH_USER/$ITCH_GAME:html5 ${versionArgument}
          fi
          if [[ -z "$WIN"]]; then
              echo "butler push \"$BASE_URL/$WIN\" $ITCH_USER/$ITCH_GAME:windows ${versionArgument}"
              butler push "$BASE_URL/$WIN" $ITCH_USER/$ITCH_GAME:windows ${versionArgument}
          fi
          if [[ -z "$OSX"]]; then
              echo "butler push \"$BASE_URL/$OSX\" $ITCH_USER/$ITCH_GAME:mac ${versionArgument}"
              butler push "$BASE_URL/$OSX" $ITCH_USER/$ITCH_GAME:mac ${versionArgument}
          fi
          if [[ -z "$LNX"]]; then
              echo "butler push \"$BASE_URL/$LNX\" $ITCH_USER/$ITCH_GAME:linux ${versionArgument}"
              butler push "$BASE_URL/$LNX" $ITCH_USER/$ITCH_GAME:linux ${versionArgument}
          fi
          if [[ -z "$ANDROID"]]; then
              echo "butler push \"$BASE_URL/$LNX\" $ITCH_USER/$ITCH_GAME:android ${versionArgument}"
              butler push "$BASE_URL/$LNX" $ITCH_USER/$ITCH_GAME:android ${versionArgument}
          fi
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_USER: pixelbyte
          BASE_URL: ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.event.inputs.tag_name }}
          ITCH_GAME: example-project
          HTML5: HTML5.zip
          WIN: Windows.zip
          # OSX: Mac-Osx.zip
          # LNX: Linux.zip
          # ANDROID: Android.zip
          #Set the itch deploy version to the tag text
          #assumes  we use this step in a workflow with a tag_version step
          VERSION: ${{ github.event.inputs.tag_name }}