name: godot-export
on:
  workflow_call:
    inputs:
      godot_download_sub_path:
        # to get this path right, goto: https://downloads.tuxfamily.org/godotengine/
        description: 'The rest of the url from which to download Godot and templates.'
        required: true
        type: string
      exporting_win_build:
        description: 'Only set to true if exporting a win build in export_presets.cfg. When false, exporting is sped up significantly.'
        default: true
        required: false
        type: boolean
jobs:
  godot_export:
    runs-on: ubuntu-latest
    name: Godot Export
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          lfs: true
      - name: Determine Export names
        id: exportInfo
        # uses: actions/setup-python@v2
        # https://github.com/marketplace/actions/run-python-script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
              import os
              from configparser import ConfigParser
              rel_proj_path = os.environ["relative_project_path"]
              set_output("win_export", "false")
              
              if rel_proj_path is None:
                error("relative_project_path was not specified!")
                stop_commands()
                exit(1)

              cfgFilename = os.path.join(rel_proj_path, "export_presets.cfg")
              cfg = ConfigParser()
              cfg.read(cfgFilename)
              # Grab only the valid sections we want 
              validSections = list(filter(lambda t : not t.endswith('options') and t.startswith('preset'), cfg.sections()))

              for section in validSections:
                name = cfg.get(section, 'name').replace('"','')
                platform = cfg.get(section, 'platform').replace('"','')
                print(f"Found {name}.zip on platform '{platform}'")
                if platform == "Windows Desktop":
                  set_output("win_export", "true")
                  set_output("win_artifact", f"{name}.zip")
                elif platform == "HTML5":
                  set_output("html5_artifact", f"{name}.zip")
                elif platform == "Mac OSX":
                  set_output("mac_artifact", f"{name}.zip")
                elif platform == "Linux/X11":
                  set_output("linux_artifact", f"{name}.zip")
                elif platform == "Android":
                  set_output("android_artifact", f"{name}.zip")
        env:
          relative_project_path: ./project
      - name: install wine
        id: install_wine
        # Only run this if the export info tells us to (i.e. we are exporting an windows build)
        if: steps.exportInfo.win_export
        run: |
          sudo apt install wine64
          echo ::set-output name=WINE_PATH::$(which wine64)
      - name: export game
        id: export
        uses: firebelley/godot-export@v4.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ inputs.godot_download_sub_path }}_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ inputs.godot_download_sub_path }}_export_templates.tpz
          relative_project_path: ./project
          use_preset_export_path: true
          archive_output: true
          wine_path: ${{steps.install_wine.outputs.WINE_PATH }}
      - name: create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action