name: godot-export
on:
  workflow_call:
    inputs:
      # tag_name:
      #   description: 'Name of the tag to post the export results to'
      #   required: true
      #   type: string
      godot_download_sub_path:
        # to get this path right, goto: https://downloads.tuxfamily.org/godotengine/
        description: 'The rest of the url from which to download Godot and templates.'
        required: true
        type: string
      exporting_win_build:
        description: 'Only set to true if exporting a win build in export_presets.cfg. When false, this speeds up exporting significantly.'
        default: true
        required: false
        type: boolean
jobs:
  godot_export:
    runs-on: ubuntu-latest
    name: Godot Export
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          lfs: true
      - name: install wine
        id: install_wine
        # Only run this if exporting_win_build == true
        if: inputs.exporting_win_build
        run: |
          sudo apt install wine64
          echo ::set-output name=WINE_PATH::$(which wine64)
      - name: export game
        id: export
        uses: firebelley/godot-export@v4.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ inputs.godot_download_sub_path }}_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ inputs.godot_download_sub_path }}_export_templates.tpz
          relative_project_path: ./project
          use_preset_export_path: true
          archive_output: true
          #Only Specify this IF YOU ARE EXPORTING A WINDOWS BUILD
          wine_path: ${{steps.install_wine.outputs.WINE_PATH }}
      - name: create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          # tag_name: ${{ inputs.tag_name }}
          files: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action