name: javascript-test
on:
  workflow_dispatch:
jobs:
  test_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            function parseINIString(data){
                var regex = {
                    section: /^\s*\[\s*([^\]]*)\s*\]\s*$/,
                    param: /^\s*([^=]+?)\s*=\s*(.*?)\s*$/,
                    comment: /^\s*;.*$/
                };
                var value = {};
                var lines = data.split(/[\r\n]+/);
                var section = null;
                lines.forEach(function(line){
                    if(regex.comment.test(line)){
                        return;
                    }else if(regex.param.test(line)){
                        var match = line.match(regex.param);
                        if(section){
                            value[section][match[1]] = match[2];
                        }else{
                            value[match[1]] = match[2];
                        }
                    }else if(regex.section.test(line)){
                        var match = line.match(regex.section);
                        value[match[1]] = {};
                        section = match[1];
                    }else if(line.length == 0 && section){
                        section = null;
                    };
                });
                return value;
            }

            try {
                var data = fs.readFileSync('export_presets.cfg', 'utf8');
                var ini = parseINIString(data);

                //Get the valid sections only
                var valid_sections = []
                var keys = Object.keys(ini)
                for (let i = 0; i < keys.length; i++){
                    if(!keys[i].endsWith('.options'))
                        valid_sections.push(keys[i])
                }
                //Compose all the sections and their output names
                var data = []
                valid_sections.forEach(section => {
                    console.log(section)
                    var d = { name : ini[section]['name'].replace(/"/g,''), platform: ini[section]['platform'].replace(/"/g,'') }
                    data.push(d)
                    // console.log(d)
                });
            } 
            catch(e) {
                console.error(e);
            }