name: javascript-test
on:
  workflow_dispatch:
jobs:
  test_javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Run javascript
        run: |
          const core = require('@actions/core');
          core.error('This is a bad error. This will also fail the build.')
