name: manual-itch-deploy
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag where the exports are'
        required: true
        type: string
      project_name:
        description: 'Name of the project on itch.io'
        required: true
        type: string
      itch_ver:
        description: 'Name of the itch version'
        required: false
        type: string
      html5_archive:
        description: 'Name of the html5 export archive.'
        required: false
        default: ""
        type: string
      win_archive:
        description: 'Name of the windows export archive.'
        required: false
        default: ""
        type: string
jobs:
  # get:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ inputs.tag_name }}
  #     - name: Get Version
  #       id: ver
  #       uses: battila7/get-version-action@v2
  #     - name: Get Godot Project Info
  #       id: project_info
  #       uses: pbytestudios/Godot-info-action@master
  #       with:
  #         relative_project_path: ./project
  itch_deploy:
    uses: ./.github/workflows/itch-deploy.yml
    with:
      itch_project: ${{ inputs.project_name }}
      version_string: ${{ inputs.itch_ver }}
      tag_name: ${{ inputs.tag_name }}
      html5_archive: ${{ inputs.html5_archive }}
      win_archive: ${{ inputs.win_archive }}
    #THIS IS CRITICAL!
    secrets: inherit