name: manual-itch-deploy
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag where the exports are'
        required: true
        type: string
      itch_ver:
        description: 'Name of the itch version'
        required: false
        type: string
jobs:
  itch_deploy:
    uses: ./.github/workflows/itch-deploy.yml
    with:
      itch_project: example-project
      version_string: ${{ inputs.itch_ver }}
      tag_name: ${{ inputs.tag_name }}
    secrets: inherit