name: manual-itch-deploy
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag where the exports are'
        required: true
        type: string
jobs:
  get_it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag_name }}
      - name: Get Version
        id: ver
        uses: battila7/get-version-action@v2
      - name: Get Godot Project Info
        id: project_info
        uses: pbytestudios/Godot-info-action@master
        with:
          relative_project_path: ./project
      - name: Deploy to Itch
        uses: ./.github/workflows/itch-deploy.yml
        with:
          itch_project: example-project
          version_string: ${{ steps.ver.outputs.version-without-v }}
          tag_name: ${{ inputs.tag_name }}
          win_archive: ${{ steps.project_info.outputs.windows_artifact }}
          html5_archive: ${{ steps.project_info.outputs.html5_artifact }}
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}