name: python-test
on:
  workflow_dispatch:
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        # - uses: actions/setup-python@v2
        - uses: jannekem/run-python-script-action@v1
          with:
            script: |
                import os
                from configparser import ConfigParser
                cfg = ConfigParser()
                print(f'relative_dir: {get_input("relative_project_path")}')
                print("Directory contents:")
                for f in os.listdir():
                    print(f)
            relative_project_path: ./project