name: manual-test-job-outputs
on:
  workflow_dispatch:
jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_ver.outputs.version }}
      version-without-v: ${{ steps.get_ver.outputs.version-without-v }}
    steps:
      #https://github.com/marketplace/actions/get-version
      - name: Get Version
        id: get_ver
        uses: battila7/get-version-action@v2
  e_version:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
     - name: Hello there
       id: display
       run: echo Hello ${{ needs.get_version.outputs.version }}