name: manual-test-job-outputs
on:
  workflow_dispatch:
jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_ver.version }}
      version-without-v: ${{ steps.get_ver.version-without-v }}
    steps:
      #https://github.com/marketplace/actions/get-version
      - name: Get Version
        id: get_ver
        uses: battila7/get-version-action@v2
  # godot_export_on_tag:
  #   uses: ./.github/workflows/godot-export.yml
  #   with:
  #     godot_download_sub_path: 3.5/rc8/Godot_v3.5-rc8
  #     exporting_win_build: false
  e_version:
    runs-on: ubuntu-latest
    name: Hello there
    id: display
    needs: get_version
    run: echo Hello ${{ needs.get_version.outputs.version }}